version: '2.4'

x-spark-worker: 
    &spark-worker
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    depends_on: 
        - spark-master
    environment: 
        - SPARK_MASTER=spark://spark-master:7077

services:

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        env_file: 
            - ./hadoop-hive.env
        volumes: 
            - namenode:/hadoop/dfs/name
        ports: 
            - 50070:50070
        environment:
            - CLUSTER_NAME=test

    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
        env_file: 
            - ./hadoop-hive.env
        depends_on: 
            - namenode
        volumes: 
            - datanode:/hadoop/dfs/data
        ports: 
            - 50075:50075
        environment:
            SERVICE_PRECONDITION: namenode:50070

    hive-server:
        image: bde2020/hive:2.3.2-postgresql-metastore
        env_file:
            - ./hadoop-hive.env
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hive-metastore/metastore
            SERVICE_PRECONDITION: hive-metastore:9083
        ports:
            - 10000:10000

    hive-metastore:
        image: bde2020/hive:2.3.2-postgresql-metastore
        env_file:
            - ./hadoop-hive.env
        command: /opt/hive/bin/hive --service metastore
        environment:
            SERVICE_PRECONDITION: namenode:50070 datanode:50075 hive-metastore-postgresql:5432
        ports:
            - 9083:9083

    hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:2.3.0

    presto-coordinator:
        image: shawnzhu/prestodb:0.181
        ports:
            - 9090:8080

    spark-master:
        image: bde2020/spark-master:2.4.5-hadoop2.7
        ports: 
            - 8080:8080
            - 7077:7077
        environment: 
            - ENABLE_INIT_DAEMON=false

    spark-worker-1:
        <<: *spark-worker
        ports: 
            - 8081:8081

    app:
        build: 
            context: ./app/.
        environment: 
            - ENABLE_INIT_DAEMON=false

volumes:
    namenode:
    datanode:
