version: '2.4'

x-spark-worker: 
    &spark-worker
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    restart: always
    depends_on: 
        - spark-master
    environment: 
        - SPARK_MASTER=spark://spark-master:7077

services:

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        restart: always
        ports:
          - 9870:9870
          - 9000:9000
        volumes:
          - namenode:/hadoop/dfs/name
        environment:
          - CLUSTER_NAME=test
        env_file:
          - ./local.env
    
    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        restart: always
        depends_on: 
            - namenode
        volumes:
            - datanode:/hadoop/dfs/data
        environment:
            SERVICE_PRECONDITION: "namenode:9870"
        env_file:
            - ./local.env
      
    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
        restart: always
        depends_on: 
            - datanode
            - namenode
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
        env_file:
            - ./local.env
    
    nodemanager1:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
        restart: always
        depends_on: 
            - datanode
            - namenode
            - resourcemanager
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
        env_file:
            - ./local.env
      
    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
        restart: always
        depends_on: 
            - datanode
            - namenode
            - resourcemanager
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
        volumes:
            - historyserver:/hadoop/yarn/timeline
        env_file:
            - ./local.env

    hue:
        image: bde2020/hdfs-filebrowser:3.11
        restart: always
        depends_on: 
            - namenode
        environment:
            - NAMENODE_HOST=namenode
        ports:
            - 8088:8088

    hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:2.3.0
        restart: always

    hive-metastore:
        image: bde2020/hive:2.3.2-postgresql-metastore
        restart: always
        depends_on: 
            - datanode
            - namenode
            - hive-metastore-postgresql
        env_file:
            - ./local.env
        command: /opt/hive/bin/hive --service metastore
        environment:
            SERVICE_PRECONDITION: namenode:9000 namenode:9870 datanode:9864 hive-metastore-postgresql:5432
        ports:
            - 9083:9083

    hive-server:
        image: bde2020/hive:2.3.2-postgresql-metastore
        restart: always
        depends_on: 
            - hive-metastore
        env_file:
            - ./local.env
        volumes: 
            - ./data:/data
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hive-metastore/metastore
            SERVICE_PRECONDITION: hive-metastore:9083
        ports:
            - 10000:10000

    spark-master:
        image: bde2020/spark-master:2.4.5-hadoop2.7
        restart: always
        ports: 
            - 8080:8080
            - 7077:7077
        environment: 
            - ENABLE_INIT_DAEMON=false
    
    spark-worker-1:
        <<: *spark-worker
        ports: 
            - 8081:8081

volumes:
    namenode:
    datanode:
    historyserver:
